version: '3.8'
services:
  ai-dungeon:
    build:
      context: .
      # args:
      #   - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    ports:
      - "7860:7860"
    environment:
      - PYTHONUNBUFFERED=1
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    secrets:
      - hf_token
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]