name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs track "*.gif"
          git config lfs.https://huggingface.co/spaces/Prgrmmer/ai-dungeon.locksverify false


      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global credential.helper store
          echo "https://Prgrmmer:${{ secrets.HF_TOKEN }}@huggingface.co" > ~/.git-credentials


      - name: Login to Hugging Face
        run: |
          pip install --upgrade huggingface_hub
          huggingface-cli login --token ${{ secrets.HUGGINGFACE_API_KEY }}
   
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git add .gitattributes
          git commit -m "Update LFS tracking" || true
          git remote set-url origin https://Prgrmmer:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Prgrmmer/ai-dungeon
          git lfs push --all origin main
          git push origin main